/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroLiderRouteImport } from './routes/cadastro-lider'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated.whatsapp'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedQrcodeLiderRouteImport } from './routes/_authenticated.qrcode-lider'
import { Route as AuthenticatedPrioridadesRouteImport } from './routes/_authenticated.prioridades'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated.mensagens'
import { Route as AuthenticatedMapaRjRouteImport } from './routes/_authenticated.mapa-rj'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated.mapa'
import { Route as AuthenticatedLiderancasRouteImport } from './routes/_authenticated.liderancas'
import { Route as AuthenticatedInteracoesRouteImport } from './routes/_authenticated.interacoes'
import { Route as AuthenticatedEmissaoContratoRouteImport } from './routes/_authenticated.emissao-contrato'
import { Route as AuthenticatedEleitoresRouteImport } from './routes/_authenticated.eleitores'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCapturaRouteImport } from './routes/_authenticated.captura'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroLiderRoute = CadastroLiderRouteImport.update({
  id: '/cadastro-lider',
  path: '/cadastro-lider',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQrcodeLiderRoute =
  AuthenticatedQrcodeLiderRouteImport.update({
    id: '/qrcode-lider',
    path: '/qrcode-lider',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrioridadesRoute =
  AuthenticatedPrioridadesRouteImport.update({
    id: '/prioridades',
    path: '/prioridades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaRjRoute = AuthenticatedMapaRjRouteImport.update({
  id: '/mapa-rj',
  path: '/mapa-rj',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiderancasRoute = AuthenticatedLiderancasRouteImport.update({
  id: '/liderancas',
  path: '/liderancas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInteracoesRoute = AuthenticatedInteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmissaoContratoRoute =
  AuthenticatedEmissaoContratoRouteImport.update({
    id: '/emissao-contrato',
    path: '/emissao-contrato',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEleitoresRoute = AuthenticatedEleitoresRouteImport.update({
  id: '/eleitores',
  path: '/eleitores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCapturaRoute = AuthenticatedCapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-lider': typeof CadastroLiderRoute
  '/login': typeof LoginRoute
  '/captura': typeof AuthenticatedCapturaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eleitores': typeof AuthenticatedEleitoresRoute
  '/emissao-contrato': typeof AuthenticatedEmissaoContratoRoute
  '/interacoes': typeof AuthenticatedInteracoesRoute
  '/liderancas': typeof AuthenticatedLiderancasRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mapa-rj': typeof AuthenticatedMapaRjRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/prioridades': typeof AuthenticatedPrioridadesRoute
  '/qrcode-lider': typeof AuthenticatedQrcodeLiderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-lider': typeof CadastroLiderRoute
  '/login': typeof LoginRoute
  '/captura': typeof AuthenticatedCapturaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eleitores': typeof AuthenticatedEleitoresRoute
  '/emissao-contrato': typeof AuthenticatedEmissaoContratoRoute
  '/interacoes': typeof AuthenticatedInteracoesRoute
  '/liderancas': typeof AuthenticatedLiderancasRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mapa-rj': typeof AuthenticatedMapaRjRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/prioridades': typeof AuthenticatedPrioridadesRoute
  '/qrcode-lider': typeof AuthenticatedQrcodeLiderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cadastro-lider': typeof CadastroLiderRoute
  '/login': typeof LoginRoute
  '/_authenticated/captura': typeof AuthenticatedCapturaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eleitores': typeof AuthenticatedEleitoresRoute
  '/_authenticated/emissao-contrato': typeof AuthenticatedEmissaoContratoRoute
  '/_authenticated/interacoes': typeof AuthenticatedInteracoesRoute
  '/_authenticated/liderancas': typeof AuthenticatedLiderancasRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/mapa-rj': typeof AuthenticatedMapaRjRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/prioridades': typeof AuthenticatedPrioridadesRoute
  '/_authenticated/qrcode-lider': typeof AuthenticatedQrcodeLiderRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cadastro-lider'
    | '/login'
    | '/captura'
    | '/dashboard'
    | '/eleitores'
    | '/emissao-contrato'
    | '/interacoes'
    | '/liderancas'
    | '/mapa'
    | '/mapa-rj'
    | '/mensagens'
    | '/prioridades'
    | '/qrcode-lider'
    | '/settings'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cadastro-lider'
    | '/login'
    | '/captura'
    | '/dashboard'
    | '/eleitores'
    | '/emissao-contrato'
    | '/interacoes'
    | '/liderancas'
    | '/mapa'
    | '/mapa-rj'
    | '/mensagens'
    | '/prioridades'
    | '/qrcode-lider'
    | '/settings'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/cadastro-lider'
    | '/login'
    | '/_authenticated/captura'
    | '/_authenticated/dashboard'
    | '/_authenticated/eleitores'
    | '/_authenticated/emissao-contrato'
    | '/_authenticated/interacoes'
    | '/_authenticated/liderancas'
    | '/_authenticated/mapa'
    | '/_authenticated/mapa-rj'
    | '/_authenticated/mensagens'
    | '/_authenticated/prioridades'
    | '/_authenticated/qrcode-lider'
    | '/_authenticated/settings'
    | '/_authenticated/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CadastroLiderRoute: typeof CadastroLiderRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-lider': {
      id: '/cadastro-lider'
      path: '/cadastro-lider'
      fullPath: '/cadastro-lider'
      preLoaderRoute: typeof CadastroLiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qrcode-lider': {
      id: '/_authenticated/qrcode-lider'
      path: '/qrcode-lider'
      fullPath: '/qrcode-lider'
      preLoaderRoute: typeof AuthenticatedQrcodeLiderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prioridades': {
      id: '/_authenticated/prioridades'
      path: '/prioridades'
      fullPath: '/prioridades'
      preLoaderRoute: typeof AuthenticatedPrioridadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa-rj': {
      id: '/_authenticated/mapa-rj'
      path: '/mapa-rj'
      fullPath: '/mapa-rj'
      preLoaderRoute: typeof AuthenticatedMapaRjRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/liderancas': {
      id: '/_authenticated/liderancas'
      path: '/liderancas'
      fullPath: '/liderancas'
      preLoaderRoute: typeof AuthenticatedLiderancasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interacoes': {
      id: '/_authenticated/interacoes'
      path: '/interacoes'
      fullPath: '/interacoes'
      preLoaderRoute: typeof AuthenticatedInteracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emissao-contrato': {
      id: '/_authenticated/emissao-contrato'
      path: '/emissao-contrato'
      fullPath: '/emissao-contrato'
      preLoaderRoute: typeof AuthenticatedEmissaoContratoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eleitores': {
      id: '/_authenticated/eleitores'
      path: '/eleitores'
      fullPath: '/eleitores'
      preLoaderRoute: typeof AuthenticatedEleitoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/captura': {
      id: '/_authenticated/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof AuthenticatedCapturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCapturaRoute: typeof AuthenticatedCapturaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEleitoresRoute: typeof AuthenticatedEleitoresRoute
  AuthenticatedEmissaoContratoRoute: typeof AuthenticatedEmissaoContratoRoute
  AuthenticatedInteracoesRoute: typeof AuthenticatedInteracoesRoute
  AuthenticatedLiderancasRoute: typeof AuthenticatedLiderancasRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMapaRjRoute: typeof AuthenticatedMapaRjRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPrioridadesRoute: typeof AuthenticatedPrioridadesRoute
  AuthenticatedQrcodeLiderRoute: typeof AuthenticatedQrcodeLiderRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCapturaRoute: AuthenticatedCapturaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEleitoresRoute: AuthenticatedEleitoresRoute,
  AuthenticatedEmissaoContratoRoute: AuthenticatedEmissaoContratoRoute,
  AuthenticatedInteracoesRoute: AuthenticatedInteracoesRoute,
  AuthenticatedLiderancasRoute: AuthenticatedLiderancasRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMapaRjRoute: AuthenticatedMapaRjRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPrioridadesRoute: AuthenticatedPrioridadesRoute,
  AuthenticatedQrcodeLiderRoute: AuthenticatedQrcodeLiderRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CadastroLiderRoute: CadastroLiderRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
